name: OpenAPI
url: https://www.openapis.org/
description: The OpenAPI Specification allows the description of a remote API accessible through HTTP or HTTP-like protocols.
prefix: OpenApi
namespace: io.apicurio.datamodels.openapi
versions:
  - $ref: ./openapi/openapi-2.0.yaml
  - $ref: ./openapi/openapi-3.0.yaml
  - $ref: ./openapi/openapi-3.1.yaml
  